### ISSUE TITLE
gute start url zum scrapen

### ISSUE THREAD

**Issue by hejjoe** [ReggaePanda/bt-scraper#5]
unter http://dipbt.bundestag.de/extrakt/ba/ sind alle beratungsabläufe seit der 8. wp gut zugänglich.

**Comment by ManAnRuck** [comment]
@hejjoe Hey! das ist Ja Mega! das kannte ich noch nicht. Vielen dank schonmal.
bei den Sachen in HTML Version ist mir nur aufgefallen, dass die etwas länger brauchen bis sie erreichbar sind als beim dip selbst. Aber da müssten wir mal beobachten wie lange das wäre. Wenn das vertretbar wäre, ist dein Link ein riesen Geschenk mit welchem wir den scraper nochmal um ein vielfaches optimieren können!
