### ISSUE TITLE
Scraper für Debattenprotokolle nutzen

### ISSUE THREAD

**Issue by Kaleidophon** [ReggaePanda/bt-scraper#9]
Hey, kurze Frage zum Projekt: Kann der Scraper genutzt werden um die Debattenprotokolle des Bundestages in JSON zu generieren? Das war mir nach einigem Herumprobieren nicht ganz klar.
Danke für jegliche Hilfe!

**Comment by ManAnRuck** [comment]
@Kaleidophon Hi, wenn du die Plenarprotokolle selbst meinst, leider nicht. Es werden derzeit nur die Vorgänge aus dem dip21 des Bundestages gescrapet. Sämtliche Dokumente sind danach nur als Link (zum Bundestag-Original) vorhanden. Falls du jedoch was in die Richtung umsetzen würdest, würden wir uns auch sehr drüber freuen 😃

**Comment by Kaleidophon** [comment]
@ReggaePanda Ich habe es mal versucht, aber per Hand robuste Regeln zu schreiben ist unglaublich deprimierend und aufwendig. Meines Wissens gibt bereit einen Parser, er scheint allerdings ziemlich grob, vermutlich aufgrund des obigen Grundes.
